### PR TITLE
Linux(Debian based) Install script.

### PR DESCRIPTION
**Pull request by Mrmagicpie**
Wow, it's me! Making a commit to world's repo? am I even allowed to do this? not sure, anyway, specified in the readme its debian based bc not all linux is the same and uh, oh, the install script too. also, have you noticed, im using more punctuation but less actual other grammar stuff? wack.

### CODE REVIEW

**Comment by Mrmagicpie** [comment]
update! fxc said i was allowed to make this pr

**Comment by micah612** [comment]
:o I'm not gonna merge so Shoeanah dosent screech, she will

**Comment by Mrmagicpie** [comment]
:OO

**Comment by micah612** [comment]
i love how this is live chat

**Comment by Mrmagicpie** [comment]
me too

**Comment by Mrmagicpie** [comment]
:(

**Comment by Mrmagicpie** [comment]
sad

**Comment by buckydevv** [comment]
haha nice

**Pull request merged**
